apiVersion: v1
kind: Service
metadata:
  name: wordpress-wp
  namespace: wordpress
  type: 1
  labels:
    app: wordpress
    daemon: frontend
spec:
  selector:
    app: wordpress
    daemon: frontend
  ports:
  - port: 80
  type: ClusterIP
